### ISSUE TITLE
className.split()

### ISSUE THREAD

**Issue by henebb** [DHTMLX/scheduler#19] opened 2016-04-20 11:42 UTC
Hi! I have inserted an svg in an element in the scheduler. I get javascript-error when there's className.split(). Because for svg-elements, the className property isn't a string.

Example:
https://github.com/DHTMLX/scheduler/blob/master/codebase/sources/dhtmlxscheduler.js#L2551

A solution to this might be to go up until we find an HTMLElement before we use className like that.
E.g.
`src = src || (e.target || e.srcElement);
while (!(src instanceof HTMLElement)) {
   src = src.parentElement;
}
var classname = src.className && src.className.split(" ")[0];`

Perhaps there are more elegant solutions to this?

To reproduce: call _on_mouse_down() with an svg-element as src.

**Comment by henebb** [comment] 2016-04-20 11:52
Update: need to check if src might be an instanceof Document as well

`while (!(src instanceof HTMLElement || src instanceof Document))`

Given this is a good solution :-)

**Comment by AlexKlimenkov** [comment] 2016-04-20 14:21
Hi! thanks, the issue is confirmed.
That line may be not the only problematic place since detecting target element by a class name is used quite commonly within the component.
I think we had the similar issue with dhtmlxGantt and ended up creating a helper for retrieving class name from a DOM element (className of svg element is an object, but we can get string from className.baseVal property) - 
https://github.com/DHTMLX/gantt/blob/v4.0.0/codebase/sources/dhtmlxgantt.js#L7978
So we'll reuse that code in a scheduler. I'll give you an update when the fix is ready, it will be a bit later today or tomorrow

**Comment by henebb** [comment] 2016-04-20 14:43
Great! I'm not in such hurry :-) But thanks anyway!

**Comment by AlexKlimenkov** [comment] 2016-04-21 17:49
Hi, the bug is fixed in a dev version, so the next update will contain a fix.
I've sent you a PM at forum.dhtmlx.com with a link to the latest build

**Closed by AlexKlimenkov** 2016-04-21 17:49 UTC
