### ISSUE TITLE
Javascript error when using custom icons for Next/Previous buttons

### ISSUE THREAD

**Issue by beaudesigns** [DHTMLX/scheduler#23] opened 2016-05-31 14:22 UTC
Inside the `dhx_cal_prev_button` and `dhx_cal_next_button` buttons, I've implemented custom SVG icons to match our theme. However, SVG `className` does not have a `split()` javascript method.

https://github.com/DHTMLX/scheduler/blob/master/codebase/sources/dhtmlxscheduler.js#L2551

This results in an error when clicking the icons, since the event bubbles up from the SVG as the event source. Adding a simple check to make sure the `split()` method exists would fix this.

```
var classname = src.className && src.className.split && src.className.split(" ")[0];
```

Thanks!

**Comment by beaudesigns** [comment] 2016-05-31 15:10
The same is true of

https://github.com/DHTMLX/scheduler/blob/master/codebase/sources/dhtmlxscheduler.js#L2223

var name = (src.className && src.className ? src.className : "").split(" ")[0];

**Comment by AlexKlimenkov** [comment] 2016-05-31 15:21
Hi,
the issue is already fixed in dev version, this repository will be updated as soon as we publish next minor or major update.
Discussed here https://github.com/DHTMLX/scheduler/issues/19

**Closed by AlexKlimenkov** 2016-05-31 15:21 UTC

**Comment by beaudesigns** [comment] 2016-05-31 15:25
Great, thank you!
