### ISSUE TITLE
Touch-handling: double-tap calls dbl_click even though dblclick_create is false

### ISSUE THREAD

**Issue by henebb** [DHTMLX/scheduler#18] opened 2016-04-11 14:59 UTC
On touch-devices, when I double-tap.

Look at line 5876: https://github.com/DHTMLX/scheduler/blob/master/codebase/sources/dhtmlxscheduler.js#L5876

If I've set config.dblclick_create = false, I don't expect that scheduler._click.dhx_cal_data() to be called because that might potentially trigger the lightbox to show.

**Comment by AlexKlimenkov** [comment] 2016-04-12 14:32
Hello,
I'm not sure if it's unexpected since it's the very same that happens when you do a regular double-click in a browser - you get two successive 'click' events followed by 'doubleclick' event. The same event order is used for touch support in dhtmlxScheduler.
Do you have a particular use case when it causes an error?

**Comment by henebb** [comment] 2016-04-12 14:56
This is on version 4.3.25. Don't know how to demo that version online. But if I set scheduler.config.dblclick_create to false, it seems that it's still possible to double-tap (on e.g.an iPad) to create events.

**Comment by AlexKlimenkov** [comment] 2016-04-12 15:03
Understood, we'll investigate. Hopefully, I'll be able to give you an update on the issue tomorrow or the day after

**Comment by AlexKlimenkov** [comment] 2016-04-14 14:45
We've reproduced the bug and it is fixed in the dev version. This repository will be updated as well as soon as the next minor update is published.
If you need a fixed build earlier, please either open a ticket in our support system at support.dhtmlx.com or send me a private message with your license number on the dhx forum - username "Aliaksandr" - http://forum.dhtmlx.com/memberlist.php?mode=viewprofile&u=10339

**Closed by AlexKlimenkov** 2016-04-14 14:45 UTC
